mysite/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "Polls Administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls"))
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailsView.as_view(), name="details"),
    path('result/<int:pk>', views.ResultsView.as_view(), name="result"),
    path('vote/<int:question_id>', views.vote, name="vote"),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin


# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    published_date = models.DateTimeField("date published")

    

    def __str__(self) -> str:
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self) -> bool:
        return timezone.now() - datetime.timedelta(days=1) <= self.published_date


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text

polls/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.views import generic
import polls

from polls.models import Question


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.all()


class DetailsView(generic.DetailView):
    model = Question
    template_name = 'details.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'result.html'


def index(request):
    latest_question_list = Question.objects.all()
    template = loader.get_template('index.html')
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, "index.html", context)


def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "details.html", context)


def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "result.html", context)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    selected_choice = question.choice_set.get(pk=request.POST["choice"])
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:result', args=[question.id]))

polls/templates/details.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{question.question_text}}</h1>
        </legend>
        {% for choice in question.choice_set.all %}
        <input type="radio" id="choice{{forloop.counter}}" value="{{choice.id}}" name="choice">
        <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

{% if latest_question_list %}

<ul>

    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:details' question.id  %}">
            {{ question.question_text }}
        </a>
    </li>
    {% endfor %}

</ul>

{% else %}

<p>No polls are available</p>

{% endif %}

polls/templates/result.html
<!-- <h1>{{question.question_text}}</h1>
{% for choice in question.choice_set.all %}
<span>{{choice.choice_text}}   {{choice.votes}}</span><br>
{% endfor %} -->


<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} votes</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>